name: CI Pipeline for Daydream Travel System

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          pytest tests/unit --junitxml=unit-results.xml

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: unit-results.xml

  deploy:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate Deploy to Test Environment
        run: |
          echo "✅ All tests passed. Deploying to test environment..."
          # Simulated deployment command (replace with real one)
          # For example:
          # rsync -av Daydream_Travel_System_Testing/ user@your-test-env:/var/www/test-app/
          echo "Deployment completed."